module.exports ={
    env:'dev',
    database:{
        dbName:'arslan',
        host:'localhost',
        port:3306,
        user:'root',
        password:'159753'
    },
    security:{
        //根密钥
        secretKey:'qwerdf',
        //过期时间
        expiresIn:60*60*24
    },
    wx:{
        AppID:'wxc4b1225cd546ef68',
        AppSecret:'4a5744ddd5d420deaed1be1ae323c9a8',
        LoginUrl:'https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code'
    }
}